name: eldora
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  twilio_flutter: ^0.0.9
  lottie: ^1.4.3
  page_transition: ^2.0.9
  firebase_auth:
  cloud_firestore:
  firebase_core:
  pinput: ^2.2.16
  timer_count_down: ^2.2.1
  provider: ^6.0.4
  flutter_local_notifications: ^12.0.2
  datetime_picker_formfield: ^2.0.1
  path_provider:
  sqflite:
  intl:
  speech_to_text: ^6.1.0
  get: ^4.6.5
  google_ml_kit:
  camera:
  image_picker: ^0.8.6
  avatar_glow:

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/animations/

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima_Nova_font.otf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
